config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/profile', to: 'users#profile'

  root to: 'songs#index'
  #
  # #display a list of all songs
  # get '/songs', to: 'songs#index', as: 'songs'
  # # return an HTML form for creating a new song
  # get '/songs/new', to: 'songs#new', as:'new_song'
  # #create a new song
  # post '/songs', to: 'songs#create'
  # #display a specific song
  # get '/songs/:id', to: 'songs#show', as:'song'
  # #return an HTML form for editing a song
  # get '/songs/:id/edit', to: 'songs#edit', as: 'edit_song'
  # #update a specific song
  # put '/songs/:id', to: 'songs#update'
  # #delete a specific song
  # delete '/songs/:id', to: 'songs#destroy'

  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :song
  validates_presence_of :song
  validates_inclusion_of :rate, :in => 1..5
end

app/models/singer.rb
class Singer < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  enum privacity: [:publico,:compartido,:privado]
  belongs_to :singer
  belongs_to :album
  belongs_to :genre
  #has_many :ratings, :dependent => :destroy
  #validates :song_url, :url => true


end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    if !user_signed_in?
      @songs = Song.where(privacity:0)
    else
      @songs = Song.where.not(privacity:2)
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @user = User.find_by(id: @song.user_id)
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = current_user.songs.new(song_params)
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      #@song.ratings.create(:rate => params[:song][:rating_ids][0].to_i)
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :release, :song_url, :singer_id, :album_id,
       :genre_id,:privacity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user_songs = current_user.songs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueNota</title>
    <%= csrf_meta_tags %>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navigation"%>
    <% if notice %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-inverse ">
 <div class="container-fluid">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">QueNota</a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
             <%= current_user.email%>
             <span class="caret"></span></a>
             <ul class="dropdown-menu">
             <li><a href="/users/profile">Mis canciones</a></li>
             <li><%= link_to 'Configuración', edit_user_registration_path%></li>
             <li role="separator" class="divider"></li>
             <li>
               <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
             </li>
           </ul>
         </li>
       <%else%>
         <li>
           <%= link_to 'Iniciar sesión', new_user_session_path %>
         </li>
         <li>
           <%= link_to 'Registrarse', new_user_registration_path%>
         </li>
       <%end%>


     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>

app/views/songs/_form.html.erb
<%= form_with(model: song,local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :song_title, class: "form-control"  %>
  </div>


  <div class="form-group">
      <%= form.label :song_url %>
      <%= form.text_field :song_url, id: :song_url, class: "form-control"  %>
    </div>

  <div class="form-group">
    <%= form.label :release %>
    <%= form.date_select :release, {order: [:year],start_year:1920}, {class: "form-control"}  %>
  </div>


  <div class="form-group">
    <%= form.label :singer_id %>
    <%= form.collection_select(:singer_id, Singer.all, :id, :name,
        {:prompt => 'Please select the singer of this song'},
        {id: :song_singer_id, class: "form-control"} ) %>
  </div>

  <div class="form-group">
    <%= form.label :album_id %>
    <%= form.collection_select(:album_id, Album.all, :id, :name,
        {:prompt => 'Please select the album of this song'},
        {id: :song_album_id, class: "form-control"} ) %>
  </div>

  <div class="form-group">
    <%= form.label :genre_id %>
    <%= form.collection_select(:genre_id, Genre.all, :id, :name,
        {:prompt => 'Please select the genre of this song'},
        {id: :song_genre_id, class: "form-control"} ) %>
  </div>

  <div class="form-group">
    <%= form.label :privacity %>
    <%= form.select :privacity, Song.privacities.keys.to_a,{}, {class: "form-control"} %>
  </div>

  <div class="actions">
  <%= form.submit "Crear",class:"btn btn-primary" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Release</th>
      <th>Singer</th>
      <th>Album</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.release %></td>
        <td><%= song.singer.name %></td>
        <td><%= song.album.name %></td>
        <td><%= song.genre.name %></td>
        <td><%= link_to 'Show', song %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <div class="fixed-action-btn">
      <a href='/songs/new'class="btn-floating btn-large green">
        <i class="glyphicon glyphicon-plus"></i>
      </a>
  </div>
<%end%>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Release:</strong>
  <%= @song.release %>
</p>

<p>
  <strong>Url:</strong>
  <%= @song.song_url %>
</p>

<p>
  <strong>Singer:</strong>
  <%= @song.singer.name %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre.name %>
</p>

<p>
  <strong>Privacity:</strong>
  <%= @song.privacity %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/users/profile.html.erb
<h1>My songs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Release</th>
      <th>Url</th>
      <th>Singer</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Privacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.release %></td>
        <td><%= song.song_url %></td>
        <td><%= song.singer.name %></td>
        <td><%= song.album.name %></td>
        <td><%= song.genre.name %></td>
        <td><%= song.privacity %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="fixed-action-btn">
    <a href='/songs/new'class="btn-floating btn-large green">
      <i class="glyphicon glyphicon-plus"></i>
    </a>
</div>